<!DOCTYPE HTML>
<html>
  <head>
    <script type="text/javascript" src="/js/datatables/jquery.min.js"></script>
    <script type="text/javascript" src="/js/datatables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/js/datatables/DT_bootstrap.js"></script>
    <script type="text/javascript" src="/css/bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/js/datatables/DT_bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/css/bootstrap-responsive.min.css">
  </head>
  <body style="width: 1000px; margin-left: 10%; margin-top: 1%;"> 
    <?php echo $this->layout()->content; ?>
  </body>
</html>